### ISSUE TITLE
it.tests not filtered out during first deployment

### ISSUE THREAD

**Issue by eglistefan** [Adobe-Marketing-Cloud/aem-eclipse-developer-tools#3]
When creating a new copy of the sample-project-archetype using the wizard, although the code at [0] should filter this out the it.tests bundle is being deployed, which fails due to a missing junit dependency. The it.launcher deploys that junit dependency when the integration tests are explicitly run, but ootb it.tests should not be deployed.

[0] https://github.com/Adobe-Marketing-Cloud/aem-eclipse-developer-tools/blob/master/com.adobe.granite.ide.eclipse-ui/src/main/java/com/adobe/granite/ide/eclipse/ui/wizards/np/NewGraniteProjectWizard.java#L151

**Comment by rombert** [comment]
This issue has been fixed in the Sling IDE Tooling project ( see [SLING-4446: AbstractNewSlingApplicationWizard publishes modules which are not deployed](https://issues.apache.org/jira/browse/SLING-4446) ) and will be incorporated in the next AEM Developer Tools public release.

If you'd like to build a fix yourself, please follow the instructions from [Sling IDE Tooling - building from source](https://sling.apache.org/documentation/development/ide-tooling.html#building-from-source).
