### ISSUE TITLE
AEM->Export To Server Generates "Not Direct Child" Error

### ISSUE THREAD

**Issue by tlwhit2** [Adobe-Marketing-Cloud/aem-eclipse-developer-tools#33]
1) Create project in Eclipse with Maven Archetype 7 & Configure to deploy to local AEM Author (Filesystem mode).
2) Run Maven build once with -P autoInstallPackage to get initial deployment.
3) Make any change in ui.apps.
4) Right-click on ui.apps, choose AEM->Export to Server...
5) Choose local server.
6) Runs for a while and then generates 'not a direct child' error (Resource at path /target/classes/etc/designs/ewcmbiz/jquery/js.txt is not a direct child of /../../../../target/classes/etc/designs/ewcmbiz/jquery)

**Comment by rombert** [comment]
This issue has been fixed in the Sling IDE Tooling project ( see [SLING-4445:Don't consider files outside the content sync root when exporting a project to the server](https://issues.apache.org/jira/browse/SLING-4445) ) and will be incorporated in the next AEM Developer Tools public release.

If you'd like to build a fix yourself, please follow the instructions from [Sling IDE Tooling - building from source](https://sling.apache.org/documentation/development/ide-tooling.html#building-from-source).
