### ISSUE TITLE
Unable to save/sync while connected to server in debug mode

### ISSUE THREAD

**Issue by TylersDesk** [Adobe-Marketing-Cloud/aem-eclipse-developer-tools#34]
When I start my server I can save files locally and they are synced to the server's JCR just fine.

When I put a break point into a JSP and enter debug mode, run a page that uses the component, my debug view in Eclipse works just fine.

When I am connected in debug mode, and make changes to a file, then hit save, it attempts to sync but then fails the operation and gives me this message:

Could not publish to the server.
java.lang.NullPointerException

I am using Luna. If you need any other information let me know.

**Comment by rombert** [comment]
Thanks for the report. I've seen this as well, recently filed https://issues.apache.org/jira/browse/SLING-4374 .

**Comment by rombert** [comment]
The content sync issue has been fixed in the Sling IDE Tooling project ( see [SLING-4374: Intermittent error when publishing content](https://issues.apache.org/jira/browse/SLING-4374) ) and will be incorporated in the next AEM Developer Tools public release.

If you'd like to build a fix yourself, please follow the instructions from [Sling IDE Tooling - building from source](https://sling.apache.org/documentation/development/ide-tooling.html#building-from-source).
