### ISSUE TITLE
Finish button broken in server step of new project wizard

### ISSUE THREAD

**Issue by gabrielwalt** [Adobe-Marketing-Cloud/aem-eclipse-developer-tools#43]
If the server already exists and a new project is created, when reaching the last step where the server is to be configured, if the default choices are ok and nothing has to be modified on that screen, then the Finish button is disabled.

Work-around: change something and revert it, the Finish button can then be clicked.

**Comment by rombert** [comment]
This issue has been fixed in the Sling IDE Tooling project ( see [SLING-5081:Unable to advance in the project creation wizard if the server is pre-selected](https://issues.apache.org/jira/browse/SLING-5081) ) and will be incorporated in the next AEM Developer Tools public release.

If you'd like to build a fix yourself, please follow the instructions from [Sling IDE Tooling - building from source](https://sling.apache.org/documentation/development/ide-tooling.html#building-from-source).
