### ISSUE TITLE
Creating project in Luna and Mars results in "The server does not support version 2.4 of the J2EE Web module specification"

### ISSUE THREAD

**Issue by chaik** [Adobe-Marketing-Cloud/aem-eclipse-developer-tools#67]
Replication steps:

1) Started AEM at 4502 with debugging at port 10123
2) In Eclipse Luna or Mars, changed to AEM perspective
3) Create new project using AEM --> AEM Sample Multi-Module Property
4) selected archetype 10
5) Entered project details (I used the L313 Summit Lab information)
6) Configure the server (port 4502, debug port 10123)
7) After clicking Finish, results in: "The server does not support version 2.4 of the J2EE Web module specification"

Workaround was to not deploy when creating a new project and creating a new server separately after that (also changing port per http://www.codejava.net/servers/tomcat/how-to-change-port-numbers-for-tomcat-in-eclipse).

Some discussion on this forum topic: http://help-forums.adobe.com/content/adobeforums/en/experience-manager-forum/adobe-experience-manager.topic.1.html/forum__jr2b-hi_i_startedhaving.html

System info:

-Mac OS X (El Capitan 10.11.2)
-Running AEM 6.1 (clean install)
-Occurred on Eclipse Luna and now Mars (Version: Luna Service Release 2 (4.4.2) Build id: 20150219-0600)

-java -version
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)

javac -version
javac 1.8.0_65

**Comment by rombert** [comment]
Thanks for the detailed steps to reproduce, I'll take a look.

**Comment by rombert** [comment]
The content sync issue has been fixed in the Sling IDE Tooling project ( see [SLING-5634: Content projects automatically configured as WST projects fail to deploy](https://issues.apache.org/jira/browse/SLING-5634) ) and will be incorporated in the next AEM Developer Tools public release.

If you'd like to build a fix yourself, please follow the instructions from [Sling IDE Tooling - building from source](https://sling.apache.org/documentation/development/ide-tooling.html#building-from-source).

**Comment by ronnyfm** [comment]
Can this PR be included as well? https://github.com/Adobe-Marketing-Cloud/aem-project-archetype/pull/60

**Comment by rombert** [comment]
For the record, it was merged
